services:
    order-service:
        build:
            context: .
            dockerfile: order-service/Dockerfile.native

    storage-service:
        build:
            context: .
            dockerfile: storage-service/Dockerfile.native
