spring:
    application:
        name: erofivan-template
    profiles:
        default: local
    datasource:
        url: ${DB_URL:jdbc:postgresql://localhost:5432/testdb}
        username: ${DB_USERNAME:test}
        password: ${DB_PASSWORD:test}
    jpa:
        hibernate:
            ddl-auto: validate
        open-in-view: false
        properties:
            hibernate:
                format_sql: true
    liquibase:
        change-log: classpath:db/changelog/db.changelog-master.yaml

    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8180/realms/erofivan}
                    jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://localhost:8180/realms/erofivan/protocol/openid-connect/certs}

springdoc:
    swagger-ui:
        path: /swagger-ui.html

server:
    port: ${SERVER_PORT:8080}

logging:
    level:
        org.hibernate.SQL: info
