Args = -H:ReflectionConfigurationResources=${.}/reflect-config.json \
      -H:ResourceConfigurationResources=${.}/resource-config.json \
      --initialize-at-run-time=io.opentelemetry.sdk.internal.ThrottlingLogger \
      --initialize-at-run-time=io.opentelemetry.exporter.internal.http.HttpExporter \
      --initialize-at-run-time=io.opentelemetry.exporter.otlp.http.trace.OtlpHttpSpanExporter \
      --initialize-at-build-time=org.slf4j \
      --initialize-at-build-time=ch.qos.logback
